version: '3.5'

services:
  postgresql:
    image: postgres:12
    restart: always
    env_file:
      - .env
    networks:
      - postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-logs:/var/log/postgresql
      - ./config/initdb.d:/docker-entrypoint-initdb.d:ro
      - ./config/data:/init.data:ro

networks:
  postgres:

volumes:
  db-data:
    driver: local
  db-logs:
    driver: local